version: '3.8'

services:
  api:
    container_name: points-tracking-service
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:dev
